<!-- CREATE DATABASE PROJECT;
USE PROJECT 

CRIAÇÃO DE TABELA
CREATE TABLE `project`.`usuarios` ( `id` INT NOT NULL AUTO_INCREMENT , `nome` VARCHAR(220) NOT NULL , `email` VARCHAR(220) NOT NULL , `senha` VARCHAR(220) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB; -->
